@extends('admin.print.layout')

@section('title', 'Receipt ' . $payment->receipt_number)

@section('content')
<div class="sheet">
    <div class="head">
        <div>
            <h1>{{ optional($student->institute)->name }}</h1>
            <div class="muted">{{ optional($student->institute)->address }} {{ optional($student->institute)->city }}</div>
            <div class="muted">{{ optional($student->institute)->phone }} · {{ optional($student->institute)->email }}</div>
        </div>
        <div style="text-align: right;">
            <div style="font-size: 18px; font-weight: 600;">Fee receipt</div>
            <div class="mono" style="font-size: 16px;">{{ $payment->receipt_number }}</div>
            <div class="muted">{{ optional($payment->verified_at)->format('d M Y') }}</div>
        </div>
    </div>

    <table>
        <tr><th>Received from</th><td><strong>{{ $student->full_name }}</strong>@if($student->er_number) · <span class="mono">{{ $student->er_number }}</span>@endif</td></tr>
        <tr><th>Course</th><td>{{ optional($student->course)->name }} ({{ optional($student->course)->code }})</td></tr>
        <tr><th>Towards</th><td>{{ optional($payment->due)->fee_head ?? 'Fees' }}</td></tr>
        <tr><th>Amount</th><td class="mono" style="font-size: 18px; font-weight: 600;">{{ money_inr($payment->amount) }}</td></tr>
        <tr><th>Paid on</th><td>{{ optional($payment->paid_at)->format('d M Y') }}</td></tr>
        <tr><th>Payment method</th><td>{{ optional($payment->gateway)->name }}</td></tr>
        @if($payment->transaction_reference)<tr><th>Reference</th><td class="mono">{{ $payment->transaction_reference }}</td></tr>@endif
        @if($payment->due)<tr><th>Balance on this fee</th><td class="mono">{{ money_inr($payment->due->balance) }}</td></tr>@endif
    </table>

    <div class="sign">
        <span>Verified by {{ optional($payment->verifier)->name }}</span>
        <span>Accounts</span>
    </div>
    <p class="muted" style="margin-top: 24px; font-size: 12px;">This receipt was generated by CAMP and is valid without a seal. Keep it for your records.</p>
</div>
@endsection
